"""Initial migration: TravelPlan, TravelGuide, Reflection models

Revision ID: 3b5d4f9146f0
Revises: 
Create Date: 2026-01-11 17:41:53.113837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5d4f9146f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('spots', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('guide_generation_status', sa.String(length=50), nullable=False),
    sa.Column('reflection_generation_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_plans_status'), 'travel_plans', ['status'], unique=False)
    op.create_index(op.f('ix_travel_plans_user_id'), 'travel_plans', ['user_id'], unique=False)
    op.create_index('ix_travel_plans_user_id_status', 'travel_plans', ['user_id', 'status'], unique=False)
    op.create_table('reflections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('spot_notes', sa.JSON(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['travel_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflections_plan_id'), 'reflections', ['plan_id'], unique=True)
    op.create_index(op.f('ix_reflections_user_id'), 'reflections', ['user_id'], unique=False)
    op.create_table('travel_guides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('spot_details', sa.JSON(), nullable=False),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('map_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['travel_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_guides_plan_id'), 'travel_guides', ['plan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_guides_plan_id'), table_name='travel_guides')
    op.drop_table('travel_guides')
    op.drop_index(op.f('ix_reflections_user_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_plan_id'), table_name='reflections')
    op.drop_table('reflections')
    op.drop_index('ix_travel_plans_user_id_status', table_name='travel_plans')
    op.drop_index(op.f('ix_travel_plans_user_id'), table_name='travel_plans')
    op.drop_index(op.f('ix_travel_plans_status'), table_name='travel_plans')
    op.drop_table('travel_plans')
    # ### end Alembic commands ###
